API_TOKEN = 'PUT_TOKEN_HERE'

VK_TOKEN_LINK = 'YOU_SHOULD_CREATE_VK_APP_AND_GET_LINK_FROM_IT_TO_GET_TOKEN'

REDIS_HOST = 'PUT_HOST_HERE'
REDIS_PORT = 00000
REDIS_PASSWORD = 'PUT_PASSWORD_HERE'

QUEUE_ID = 1

URL_BASE = 'https://api.telegram.org/file/bot' + API_TOKEN + '/'
LOG_PATH = '/tmp/memstrual.log'

ADMIN_ID = 15726346
